run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
linters:
  disable-all: true
  enable:
    - deadcode
    - gocyclo
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - gofmt
    - importas
    - goconst
