name: Security Stack
description: End-to-end K8s security using Plural.
featured: true
collections:
- provider: AWS
  bundles:
  - name: kubescape-aws
    repo: kubescape
  - name: istio-aws
    repo: istio
  - name: vault-aws
    repo: vault
- provider: GCP
  bundles:
  - name: kubescape-gcp
    repo: kubescape
  - name: istio-gcp
    repo: istio
  - name: vault-gcp
    repo: vault
- provider: AZURE
  bundles:
  - name: kubescape-azure
    repo: kubescape
  - name: istio-azure
    repo: istio
  - name: vault-azure
    repo: vault