apiVersion: v1 
kind: Pod 
metadata: 
  name: plural-cli-dind-sidecar-2
  namespace: sysbox
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec: 
  runtimeClassName: sysbox-runc
  tolerations:
    - key: plural.sh/sysbox
      operator: Exists
    - key: plural.sh/capacityType
      operator: Exists
  restartPolicy: Never
  containers: 
    - name: plural-cli
      image: ghcr.io/pluralsh/plural-cli-cloud:sha-993c518
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      resources: 
        requests: 
          cpu: 10m 
          memory: 256Mi 
      env: 
      - name: DOCKER_HOST 
        value: tcp://localhost:2375 
      volumeMounts: 
        - name: docker
          mountPath: /var/lib/docker 
    - name: sysbox-dind
      image: ghcr.io/pluralsh/plural-dind:sha-993c518
      resources: 
        requests: 
          cpu: 20m 
          memory: 512Mi 
      securityContext: 
        privileged: false 
      volumeMounts: 
        - name: docker
          mountPath: /var/lib/docker 
  volumes: 
    - name: docker 
      emptyDir: {}
