apiVersion: v1
kind: Pod
metadata:
  name: plural-cloud-priv2
  namespace: sysbox
  #annotations:
  #  io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  #runtimeClassName: sysbox-runc
  containers:
  - name: plural-cloud-priv2
    image: ghcr.io/pluralsh/plural-cli-cloud:sha-0ea2f1a
    resources:
      requests:
        memory: "256Mi"
        cpu: "1m"
    securityContext:
      runAsUser: 1000
      capabilities:
        add:
          - "SYS_ADMIN"
          - "MKNOD"
          - "SYS_CHROOT"
          - "SETFCAP"
      #allowPrivilegeEscalation: false
    volumeMounts:
      - name: containers-volume
        mountPath: /var/lib/containers
  volumes:
    - name: containers-volume
      hostPath:
        path: /var/lib/containers
  tolerations:
  - key: plural.sh/sysbox
    operator: Exists
  - key: plural.sh/capacityType
    operator: Exists
  restartPolicy: Never