apiVersion: v1
kind: Pod
metadata:
  name: plural-cloud-sysbox
  namespace: sysbox
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: plural-cloud-sysbox
    image: ghcr.io/pluralsh/plural-cli-cloud:sha-f09a09f
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "1m"
    securityContext:
      #runAsUser: 1000
      capabilities:
        add:
          - "SYS_ADMIN"
          - "MKNOD"
          - "SYS_CHROOT"
          - "SETFCAP"
      #allowPrivilegeEscalation: false
  tolerations:
  - key: plural.sh/sysbox
    operator: Exists
  - key: plural.sh/capacityType
    operator: Exists
  restartPolicy: Never