name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GOPATH: /home/runner/go/
  GOBIN: /home/runner/go/bin
jobs:
  plural-up-gcp:
    name: plural up / GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
      - name: Add GOBIN to PATH
        run: echo $GOBIN >> $GITHUB_PATH
      - name: Setup Plural CLI
        run: make install-cli
      - name: Print Plural CLI version
        run: plural version
      - name: Print Terraform version
        run: terraform --version
      - name: Print Google Cloud CLI version
        run: gcloud --version
  plural-up-azure:
    name: plural up / Azure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
      - name: Add GOBIN to PATH
        run: echo $GOBIN >> $GITHUB_PATH
      - name: Setup Venom
        run: |
          curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o /usr/local/bin/venom
          chmod +x /usr/local/bin/venom
          venom version
      - name: Setup Plural CLI
        run: make install-cli
      - name: Print Plural CLI version
        run: plural version
      - name: Print Terraform version
        run: terraform --version
      - name: Print Azure CLI version
        run: az --version
      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.E2E_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.E2E_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.E2E_AZURE_SUBSCRIPTION_ID }}