name: E2E
on:
  pull_request:
    branches:
      - main
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true
      - run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get -y install terraform
      - run: |
          make install
          cp "$HOME"/bin/plural /usr/local/bin/
          chmod 755 /usr/local/bin/plural
      - run: hack/e2e/setup-plural.sh
        env:
          CLI_E2E_CONF: ${{ secrets.CLI_E2E_CONF }}
          CLI_E2E_PUBLIC_KEY: ${{ secrets.CLI_E2E_PUBLIC_KEY }}
          CLI_E2E_PRIVATE_KEY: ${{ secrets.CLI_E2E_PRIVATE_KEY }}
      - run: go test -v -race ./pkg/test/e2e/... -tags="e2e"
      - run: |
          cd $HOME/test
          plural destroy --force --commit=""
