name: Edge
on:
  schedule:
    - cron: 0 0 * * 1-5 # At 00:00 on every day-of-week from Monday through Friday
  workflow_dispatch: # On demand
  push:
    branches:
      - main
    paths:
      - cmd/command/edge/*
  pull_request:
    branches:
      - main
    paths:
      - cmd/command/edge/*
jobs:
  image:
    name: Check image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make install-cli
      - run: |
          touch cloud-config.yaml
          plural edge --url=test --token=dGVzdAo= image --cloud-config=cloud-config.yaml
