name: CI
on:
  schedule:
    - cron: 0 0 * * 1-5 # At 00:00 on every day-of-week from Monday through Friday
  workflow_dispatch: # On demand
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  contract-validation:
    name: Validate PR Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make install-cli
      - run: plural edge image --username=test --password=test --output-dir=image
